### ISSUE TITLE
"Build succeeded" when all tests failed

### ISSUE THREAD

**Issue by dima74** [bors-ng/bors-ng#1111]
Hi!
We have [this pull request](https://github.com/intellij-rust/intellij-rust/pull/6558) merged by bors, though looks like that bors shouldn't merge it, because tests actually failed. Here is ["build succeeded" message](https://github.com/intellij-rust/intellij-rust/pull/6558#issuecomment-751242039), but if you click on `check` workflow link, we can see that almost all tests actually failed.

**Comment by Undin** [comment]
I suppose a little bit more correct question is "Why bors merged PR if the corresponding [check](https://github.com/intellij-rust/intellij-rust/runs/1608503639) was canceled (because some previous steps failed)?".
See [status settings](https://github.com/intellij-rust/intellij-rust/blob/18891f4fa3f3d072f29d28c095b4d9e221c495c3/bors.toml#L1-L3) in our `bors.toml`

**Comment by notriddle** [comment]
I bet https://github.com/bors-ng/bors-ng/pull/1110 it’s what does it. It should be marked as a failure condition, then?

**Comment by Undin** [comment]
@notriddle Thanks for quick response!
Actually, I think both `ok` and `error` statuses are wrong here because the status of the whole workflow run depends on status of each job in the workflow. For test purposes, I slightly modified our current workflow in my own fork to skip the latest job if everything is fine in dependencies - https://github.com/Undin/intellij-rust/actions/runs/444320109. As you can see, github supposes that this run is successful although the latest job is skipped.

In our `check` workflow, the final `check` job was introduced to simplify interaction with `bors` - not to specify all jobs (that github maps to checks) in `status` array of `bors.toml` because it's quite easy to forget updating the array after changes in the workflow. So in our case, `skipped -> error` mapping will help but as I mentioned above, it can break something else. Looks like the most correct solution is to check the status of the whole workflow run instead of an individual check. Is it possible to configure `bors` in such way?

**Comment by notriddle** [comment]
> Looks like the most correct solution is to check the status of the whole workflow run instead of an individual check. Is it possible to configure bors in such way?

It’s not possible right now. I agree that a feature like that is desirable, but I guess “skipped = error” is the most correct choice for the case where a step that you specifically named was canceled.

To get what you actually want, you need to name the entire workflow, instead of just naming the individual step. Backwards compatibility mandates that the current setup needs to work, and since your workflow worked before, I’ll try to unbreak it.

**Comment by notriddle** [comment]
See also: https://github.com/bors-ng/bors-ng/issues/946
