### ISSUE TITLE
new "Mergeable" column incorrect?

### ISSUE THREAD

**Issue by bryangingechen** [bors-ng/bors-ng#1329]
This is in reference to [leanprover-community/mathlib](https://github.com/leanprover-community/mathlib)'s bors page: https://app.bors.tech/repositories/24316

I looked over [the "Keep track of unmergeable and draft pull requests" RFC](https://forum.bors.tech/t/keep-track-of-unmergeable-and-draft-pull-requests/556), and my impression was that the "Mergeable" column should show "Yes", "No" and "Draft", where "No" means that there's a merge conflict and "Draft" means that it's a draft PR.

Earlier, I noticed that every PR in our repository showed "Yes" in the "Mergeable" column except for two random ones which showed "No", despite the fact that we have a few open Draft PRs.

I tried the "Sync pull requests" button at the bottom, but now, all the PRs show "No" in the "Mergeable" column instead.

Hopefully this is just some kind of UI issue which won't cause all of our future batches to fail...

**Comment by notriddle** [comment]
The fact that it showed some PRs as mergeable when they actually weren't was expected. Bors just didn't backpopulate all the data. I was planning on it gradually fixing itself, because [whenever bors gets a webhook, it will extract the PR metadata that GitHub attaches to it and sync the database with it](), so every time you post a comment, push a commit, or otherwise interact with a PR, bors will fix that data up.

This also means that the bug only affects the UI, since when you make a `bors r+` comment, it fixes itself.

The sync pull requests problem is an actual problem, though. #1334 should fix it.

**Comment by bryangingechen** [comment]
Hmm, all of the PRs awaiting review seem to have disappeared from the bors page, though I see they are maybe slowly repopulating - is that related to this update somehow?

**Comment by notriddle** [comment]
Yes, I saw that too. It's running a resync job right now to fix your dashboard.

**Comment by bryangingechen** [comment]
Got it. It looks good now, thanks!
