### ISSUE TITLE
General questions about Elixir and bors-ng

### ISSUE THREAD

**Issue by Macarse** [bors-ng/bors-ng#146]
@notriddle I will take advantage of how friendly your `Getting started for contributors` is :)
My questions so far:

1) File path modules name.
Being used to Java I find hard finding other files.

Example: I am reading `BorsNG.WebhookController` @ bors_frontend/web/controllers/webhook_controller.ex
I read 
```
use BorsNG.Web
```

and after a search I find `BorsNG.Web` @ bors_frontend/lib/bors_ng/web.ex

I couldn't find a convention to file names. Is there one?

2) Something I found while searching for a file name convention is: https://github.com/rrrene/credo
After adding it to the project:

```
Analysis took 5.0 seconds (0.1s to load, 4.9s running checks)
370 mods/funs, found 189 consistency issues, 7 refactoring opportunities, 2 software design suggestions.
```
not sure if you are interested in adding a style check. Let me know and I will try fixing all warnings.

3) How to deal with code repetition? For example:
`BorsNG.Database.AttemptStatus` and `BorsNG.Database.Status` both have:

```
  def atomize_state(state) do
    case state do
      0 -> :waiting
      1 -> :running
      2 -> :ok
      3 -> :error
    end
  end

  def numberize_state(state) do
    case state do
      :waiting -> 0
      :running -> 1
      :ok -> 2
      :error -> 3
    end
  end
```
I know it's a small and it might not be even worth it, but I am not 100% of the possible solution. Module creation to handle state? Is there a bidirectional map in Elixir? 

4) Can't bors live without the db? Wouldn't you be able to understand the status of the project by reading all the PRs and base the status on bors' comments? 

Cheers!

**Comment by notriddle** [comment]
If you want to fix credo warnings, then that's awesome! Please do! I haven't bothered because there's always been something higher-priority. That and I've been lazy.

---

About file names, Elixir doesn't enforce any kind of mapping between file names and module names. I've been following what other Elixir projects seem to use, which is camel-cased version of the module name.

The exception is the web folder. Once bors-ng migrates to the next version of Phoenix (which will happen once it's out of beta), all the stuff in `web` will move to `lib`, removing that last lingering inconsistency.

---

I have no idea if there's a bidirectional​ map thing for Elixir.

---

And, finally, about bors living without a database: it's possible, but it would hit the GitHub API way more heavily. The old bors had problems with hitting rate limits. If you just want to avoid setting up Postgres, it could run out of sqlite or mnesia (I didn't do that because I wanted it to work under Heroku).

**Comment by Macarse** [comment]
Thanks for your answer!
