### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by hauleth** [bors-ng/bors-ng#199]
This is issue just to remember me to write it one day.

**Comment by ehiggs** [comment]
What work would need to be done here?

**Comment by notriddle** [comment]
It already supports CI systems other than Travis.

The bad part is that bors-ng depends heavily on GitHub's API. It uses GitHub's Data API to perform merges on the server, uses GitHub's Apps API to handle registration, uses GitHub's status and checks API as a sort of "universal CI adapter", and uses things like reviews and tags.

**Comment by notriddle** [comment]
I'm definitely not going to do this.

If you need bors-like behavior on a gitlab repo right now, you can use <https://github.com/smarkets/marge-bot>. I found this while doing research for a client while planning to do this port, but since it already exists...

It'll also be superseded by [merge trains](https://gitlab.com/gitlab-org/gitlab-ee/issues/9186) once that feature ships.
