### ISSUE TITLE
Wishlist: merge based on github review approval

### ISSUE THREAD

**Issue by anguslees** [bors-ng/bors-ng#213]
Adding a "bors r+" comment is unnecessarily cryptic in the common case now that github natively has a notion of review approval.

It would be nice if bors-ng was able to start the test/merge process based on the presence of a positive github review (and absence of any negative review) from someone in a configured list of users - without interacting through explicit "bors" comments.

**Comment by nox** [comment]
The moment I'm ready to do "bors r+" and the moment when I approve a review are often disjoint, I'm not sure this would be a good idea.

What about some code being correct, but you want to land a different PR first?

**Comment by notriddle** [comment]
@mmun and I have been talking about this issue in PM before this issue was filed. BTW, @mmun, if I get anything wrong feel free to correct it.

# Why not just want to make a configuration option

On the one hand, different projects have different norms. To some extent, they'd probably complain bitterly at the idea of changing the way they do things to fit a tool.

On the other hand, someone who contributes to multiple open-source projects would prefer if they did do things the same way. It would be especially annoying if two projects both used bors, but one was set up so that GitHub Reviews triggered bors but the other one didn't. "I know how to use bors" should be a thing.

# So, about the use cases

@mmun specifically said that he didn't want to have GitHub Reviews trigger bors, because at @ZestyZesty, PR submitters make the final call about whether it's ready. Typically, they'll solicit feedback, which means they'll get the reviews, but the submitter might just ignore the reviews and r+ themselves anyway.

@nox, on the other hand, is thinking of a more typical OSS flow, where the maintainers review pull requests from the outside. The PRs might have ordering dependencies, or perhaps just a manually-tracked priority; the point is that "LGTM" != "let's merge it now." I guess you could probably achieve what you want with "block labels," but the status quo is probably better than that.

Also, you have to admit, that GitHub reviews and Bors approval do correlate a lot.

**Comment by notriddle** [comment]
BTW, @mmun's company had [an internal RFC](https://gist.github.com/mmun/bb610d208008186e87605aa18a40c6bf) about this stuff (yes, I got permission to publish it).

**Comment by notriddle** [comment]
After a year, and I still don't want to do it, so let's make it official and close as WONTFIX.

* People who aren't familiar with `bors` should be able to figure out at least some of what's going on; the maintainer leaves a cryptic string of computer code, and then a `[bot]` (who's name is at the start of the command, just like a UNIX command or `Okay Google`) responds. Performing an action automatically when an approving Review is left doesn't [telegraph](https://tvtropes.org/pmwiki/pmwiki.php/Main/TropeTelegraphing) what's going on as well.

  * In the interest of giving the contributors a comforting green checkmark, the reviewer should leave the command in an Approving review, [like this](https://github.com/bors-ng/bors-ng/pull/550#pullrequestreview-178423606).

  * I've been tempted to add a more descriptive command name, like `bors approve`, because `bors r+` is kinda cryptic, but back when the bot was called `@aelitabot`, people complained about how much I was asking them to type.

* I want to give reviewers some level of consistency across bors-y projects. Adding merge-based-on-PR *as an option* means that if a single reviewer is involved with multiple OSS projects that all use bors, they'd have to memorize which projects work one way and which ones work the other.

* Automatically merging the pull request isn't the normal semantics of an approving GitHub Review anyway, so even if we eliminated `bors r+` entirely, it still doesn't mean that contributors and reviewers can forget that bors exists. The only way to truly eliminate this complexity is to not retrofit this thing onto the PR interface that isn't designed for it.

**Comment by Gabriella439** [comment]
I'd like to relitigate the reasoning given for not implementing this because things have changed since then.

Specifically, GitHub now natively supports [enabling auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) and the semantics of that are that the PR is automatically merged after all branch protection requirements are met (including approvals, if they're a branch protection requirement, and they typically are).

It is true that back in 2018 that "Automatically merging the pull request isn't the normal semantics of an approving GitHub Review anyway" but now (in 2023) it is very much a reasonable semantics for an approving GitHub review to lead to a PR being auto-merged.

**Comment by Gabriella439** [comment]
For what it's worth, this is the code change to mirror how GitHub's auto-merge feature works (for anyone interested in patching their own self-hosted `bors-ng` instance):

```diff
diff --git a/lib/worker/batcher.ex b/lib/worker/batcher.ex
index f835eb8..91f2e69 100644
--- a/lib/worker/batcher.ex
+++ b/lib/worker/batcher.ex
@@ -1016,14 +1016,7 @@ defmodule BorsNG.Worker.Batcher do
     case {passed_label, no_error_status, no_waiting_status, no_unset_status, passed_review,
           code_owners_approved, passed_up_to_date_review} do
       {true, true, true, true, :sufficient, true, :sufficient} -> {:ok, toml.max_batch_size}
-      {false, _, _, _, _, _, _} -> {:error, :blocked_labels}
-      {_, _, _, _, :insufficient, _, _} -> {:error, :insufficient_approvals}
-      {_, _, _, _, :failed, _, _} -> {:error, :blocked_review}
-      {_, _, _, _, _, false, _} -> {:error, :missing_code_owner_approval}
-      {_, false, _, _, _, _, _} -> {:error, :pr_status}
-      {_, _, false, _, _, _, _} -> :waiting
-      {_, _, _, false, _, _, _} -> :waiting
-      {_, _, _, _, _, _, :insufficient} -> {:error, :insufficient_up_to_date_approvals}
+      {_, _, _, _, _, _, _} -> :waiting
     end
   end
```

Basically it always waits until all criteria are satisfied and never kicks back the PR with an explicit rejection during the pre-flight stage.  Note that this will still eventually hit the `prerun_timeout` so if you want it to wait indefinitely for the criteria to be satisfied (just like GitHub does) then you'd have to make further changes to disable that timeout or just set the timeout really high.
