### ISSUE TITLE
Crash batch

### ISSUE THREAD

**Issue by carols10cents** [bors-ng/bors-ng#260]
This might be the same as #252, but I'm not sure, so I'm filing a new issue. Please feel free to close if this is the same thing.

Yesterday, I successfully `r+`ed a PR that had *some* commits (including the last commit in the PR) that were marked `[ci skip]`: https://github.com/rust-lang/crates.io/pull/895

After that, I `r+`ed a different PR that did NOT have any `[ci skip]`, and bors appears to be running forever: the status is always yellow "waiting in queue", and bors hasn't commented at all (which is different from #252 where bors commented with a timeout) https://github.com/rust-lang/crates.io/pull/942

Looking at the log in https://bors-voyager.herokuapp.com/repositories/1/log, I see:

```
Crash | batch | {:timeout,  {GenServer, :call,   [BorsNG.GitHub,    {:synthesize_commit, {{:installation, 42672}, 21365581},     {%{branch: "staging.tmp", commit_message: "[ci skip]",        parents: ["6ecbccdd217bed7d415b342302cac9aa24ef7dc9"],        tree: "5185ecd79fef9248d80ecc8561447a27effefeee"}}},    5000]}}
```

The `commit_message: "[ci skip]"` is what caught my eye.... that's already been merged, though.

`r+`ing again on #942 resulted in the same behavior.

I'm going to leave this around for a bit in case there's any useful information from the current state, but I would like to merge this PR in soon...

**Comment by notriddle** [comment]
The `[ci skip]` part is there so that Circle CI won't try to build all the intermediate stuff. That timeout might not have anything to do with the fact that the commits in this PR have it in their messages too.

This message literally means that it timed out trying to make a GitHub API call. You can try going into heroku and restarting the "web" dyno.

**Comment by notriddle** [comment]
Welp, it's not a problem with reaching out to GitHub, since `bors ping` "works".

Does it show anything waiting in the queue if you go into the dashboard? I can't see it in the backlog, since bors-voyager has private repos turned on.

**Comment by carols10cents** [comment]
> Does it show anything waiting in the queue if you go into the dashboard?

It does right after I say "bors r+":

<img width="674" alt="screen shot 2017-08-10 at 5 33 08 pm" src="https://user-images.githubusercontent.com/193874/29193288-9f7271b4-7df2-11e7-8e10-c08b8a37393e.png">



I tried restarting the heroku web dyno and then r+ing again, it seems to be running now I think?

**Comment by notriddle** [comment]
Welp, it worked.

Assuming you're not going to link any private repos to this instance of bors-ng, there's three things you'll probably want to do, in this order, to your installation:

* [Remove the `ALLOW_PRIVATE_REPOS` env variable.](https://dashboard.heroku.com/apps/bors-voyager/settings). This will prevent you from adding private repos to bors-voyager, but it also means that non-reviewers can see the queue (they still can't see stuff like crash backtraces, since I don't feel comfortable assuming that there won't be any secrets in those backtraces).
* Add the "dyno metadata" addon. This'll make it so that the footer shows the commit hash that you have deployed, instead of a totally useless version number. The only way to do this that I know of is to use the CLI command `heroku labs:enable runtime-dyno-metadata -a bors-voyager`.
  * By the way, this change can also come in handy for crates.io, which IIRC wants to add this same feature.
* Update to the latest commit from bors-ng master. This will cause the settings changes to kick in, as well as getting you a couple bug fixes.

**Comment by carols10cents** [comment]
> Add the "dyno metadata" addon.

OOOOOOHHHH NICE!!!
