### ISSUE TITLE
consider using gitter

### ISSUE THREAD

**Issue by khodzha** [bors-ng/bors-ng#276]
instead of using irc bors-ng can try adopting [gitter](https://gitter.im/)
i've never used it personally, but (maybe) its worthwhile due to persistent (no need to use 3rd party services) history?

(or maybe use discord? its quite good🤔)

**Comment by notriddle** [comment]
You can join in the IRC channel and have persistent history with https://riot.im/. It's what I'm using, and it works pretty well.

**Comment by notriddle** [comment]
OTOH, since riot actually does have a Gitter bridge, I'd be fine with running a Gitter if I knew other people would want to use it.

**Comment by jniles** [comment]
If you feel up to handling the traffic of people requesting help, it would be useful to put a [your IRC instructions](https://github.com/bors-ng/bors-ng/issues/276#issuecomment-323602242) on the README.  Gitter is useful because it makes it very clear where to get support (just go to `org/repo`).  With IRC, it is not clear where to go to ask quick questions about contributing/errors/etc.

**Comment by notriddle** [comment]
I've created the gitter organization.

**Comment by notriddle** [comment]
There's also now a forum at https://forum.bors.tech/. That's what's recommended on Starters and the Getting Started guide, now, so that should fix this issue.

**Comment by notriddle** [comment]
Anyone want to review [the announcement blog post](https://github.com/bors-ng/bors-ng.github.io/pull/25)?
