### ISSUE TITLE
Do pagination on the History/Log page

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#305]
The History page (in the `project_controller.ex` file under `def log`, and the `log.html.eex` file) shows the entire history of the given project when you first open it. It should probably have a limit on that, with an Older button on the bottom to page through it (or infinite scrolling, if you really feel fancy).

**Comment by GustavoCaso** [comment]
@notriddle I love to help on this one

**Comment by notriddle** [comment]
Go for it :+1:

**Comment by notriddle** [comment]
@GustavoCaso You still working on it?

**Comment by GustavoCaso** [comment]
Oh @notriddle completely forgot it about this, sorry about it. Sure I will work on this 😄

**Comment by xmo-odoo** [comment]
> It should probably have a limit on that, with Older and Newer buttons on the bottom to page through it.

FWIW depending on the exact modeling it could be much cheaper to only have "older" links, basically dive deeper in the history but not have any button to jump to a page or go backwards (just use the history) as that [would allow keyset pagination (aka "seek" method)](http://use-the-index-luke.com/no-offset) instead of offset pagination.

I'd expect it to be amply sufficient for a history page. Or to implement an "infinite scrolling" type of history.

**Comment by notriddle** [comment]
> FWIW depending on the exact modeling it could be much cheaper to only have "older" links, basically dive deeper in the history but not have any button to jump to a page or go backwards (just use the history) as that would allow keyset pagination (aka "seek" method) instead of offset pagination.

Sure, that's fine with me. And if you want to implement infinite-scrolling, then that's fine with me, too.
