### ISSUE TITLE
Integrate ex_format into the CI setup

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#306]
https://github.com/uohzxela/ex_format

You'll want to hook it into .taskcluster.yml, potentially by writing a script file in `scripts/` and calling it from in there. We probably want to run this check when pull requests are made against master branch and when a push is made to staging or trying branches.

**Comment by kimsaehun** [comment]
I would like to work on this issue.

However, I am unfamiliar with TaskCluster and with some of the Bors-NG project details and would like help with some of the troubles I am having.

1. I have created two task definitions, one to handle the pull request to master event and another to handle the push to staging/trying event. Is this the proper approach to handle the two events or is there a better way to handle the two cases in one task?
2. Is "notriddle/docker-phoenix-elixir-test" the correct image to specify in the payload field? I simply assumed so because the other task definitions specified said image.
3. How would I ensure that ExFormat is installed? I'm thinking that I could put `mix escript.install https://github.com/uohzxela/ex_format/raw/master/ex_format` in the command parameter of the payload field but I feel that is not most suitable location. Could this be where "potentially by writing a script file in scripts/ and calling it from in there" comes into play?

**Comment by kimsaehun** [comment]
Thanks for answers the notriddle! I have some additional question regarding the creation of a script.

It appears to be that the script directory contains bash scripts that run the docker-compose commands. However, I am also confused to as how the scripts are actually being ran. I have no experience with Docker but seeing as how there is a Docker file, could it be that Docker automatically calls these scripts? If possible, could you explain the process of how these scripts are being used or redirect me to a resource to learn the process?

Despite my confusion, I did notice that there was a setup script which sounds like a good place the code to install ExFormat in. Since installing ExFormat seems to be a part of setting up the project, rather than creating a new script, would it make sense to edit the setup script to install ExFormat?

**Comment by notriddle** [comment]
In the "payload" section of the TaskCluster YML file, there's a "command". That contains the call to one of the scripts.

The only script that is currently used is the one called "ci". The other ones are for people running locally.

**Comment by kimsaehun** [comment]
So as I was working on this issue, I ran into [a problem with ExFormat](https://github.com/uohzxela/ex_format/issues/91). The project owner's recommendation was to "have a look at the [latest code formatter](https://github.com/whatyouhide/code_formatter) that's under development by the Elixir core team."

Since ExFormat is meant to be a prototype and is not production ready, I believe this issue should be closed. 

In regards to the code formatter by the Elixir core team, it appears to only be available with Elixir 1.6 which I believe is still in development so as of currently, it doesn't seem like a solution for now.

**Comment by notriddle** [comment]
Okay.
