### ISSUE TITLE
Push commits as a user other than bors-ng

### ISSUE THREAD

**Issue by Phrohdoh** [bors-ng/bors-ng#343]
I'd like commits to master to belong to my user (@Phrohdoh).

Is this currently possible? If not is it planned?

**Comment by notriddle** [comment]
Bors-NG doesn't support that, yet. It could be added pretty easily, if you don't mind GitHub saying that "Phrohdoh authored and bors committed" (having it hide bors entirely would be more complicated, since it would have to log in with your user instead of the installation token). It hasn't been on the planning backlog, because you're the first person who asked for it.

Not sure if you're worried about this, but https://github.com/bors-ng/bors-ng/graphs/contributors doesn't misattribute all the work to bors or anything. GitHub ignores merge commits when it generates the contributor boards.

**Comment by jeffparsons** [comment]
I'm currently facing an issue related to this. I'm trying to get a private instance of Bors working with the [Buildkite CI system](https://buildkite.com), which in many cases requires that the email address associated with a commit is a "verified email" of one of the users in your Buildkite organisation.

I've opened an issue in the Buildkite organisation for discussion: https://github.com/buildkite/feedback/issues/313

But I'm really not sure what the best place is for a fix/workaround. I could imagine any of these:

- **GitHub:** let you associate a real email address with a GitHub application
- **Bors:** allow committing as another user
- **Buildkite:** some general way to play nice with GitHub applications

The other option I've considered is trying to set Bors up as an "OAuth App", because then it'd be a "real" GitHub user making the commits, and the problem would just go away.

(Here's the options:)

![screen shot 2018-02-12 at 1 05 21 pm](https://user-images.githubusercontent.com/321861/36081631-7578155e-0ff5-11e8-9f3c-e8fba3477e29.png)

Does anyone know if I'd be totally wasting my time trying that approach? If I had to make some changes to Bors to make it work, would you want to have them upstream? (I'd probably take a very different approach if this isn't a configuration you're interested in having in your tree.)

**Comment by notriddle** [comment]
Using the git data API, bors-ng can create commits that are associated with about email address that it wants (though GitHub will label them as "X authored and Y committed"). I'd be perfectly happy to accept changes that make it so that.

I'd rather not not change it to an oauth app, because there are a bunch of APIs differences between oauth apps and github apps.
