### ISSUE TITLE
The synchronize pull request button removed access for everyone!

### ISSUE THREAD

**Issue by jeff-hammel-leapyear** [bors-ng/bors-ng#368]
There's a nice blue button that says "Sync pull requests".  However, clicking on this button revoked reviewer status for everyone.  I'm fairly sure that this is not the intended feature.  

This happened three times in a row today (twice with the latest code), so it seems rather reproducible.
This used to work fine.  Now it doesn't.

**Comment by jeff-hammel-leapyear** [comment]
Our best guess is https://github.com/bors-ng/bors-ng/commit/4de3c9e5dbe2df4e7fe5667745d905fbec5a5222#diff-a64d6851c9b6e09dca9bae2641df2d88

**Comment by notriddle** [comment]
Yup, that is indeed the source of the problem. More specifically, that pull request changed the default behavior to synchronize the repo's admin list with bors's reviewer list. That's not right, because it's a breaking change and the GUI gave no indication that it was doing that.

I've pushed #369, which should revert it to the old behavior. Once the synchronization behavior is implemented, we could turn it on by default for new repos, but existing repos need to be left alone.

**Comment by danielkza** [comment]
This one was 100% on me, apologies for the inconvenience.
