### ISSUE TITLE
`required_approvals` should not use `bors.toml` in source branch

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#371]
**Background:**

What I did:

 1. Upgraded `bors-ng` to the b9770bc7af66 Docker image.
 2. Verified that `bors r+` worked on a basic pull request which modified some `README` file or something.
 2. Submitted a pull-request which added `required_approvals = 1` to my `bors.toml` file.
 3. Tried to approve it myself by commenting "bors r+" and got "👎 Rejected by too few approved reviews".

**Was happened:**

bors-ng used the `required_approvals` setting in the submitted pull request rather in the destination branch. If `required_approvals` is being used as a hard security measure (which we were hoping to do), this means that any user could relax the security requirements by simply making a pull request.

**Expected:**

That bors-ng hasn't started using the newly introduced `required_approvals = 1` setting since it actually hasn't been merged. Instead bors-ng should use the `bors.toml` file in the destination branch.

**Workaround:**

Use something like https://github.com/tink-ab/four-eyes :-)

**Comment by notriddle** [comment]
Four-eyes won't work as a workaround, because bors also uses the status line from the staging branch, just like it's using the required approvals line from the staging branch. That's intentional, so that changes to the bors.toml file get tested before they end up in master, though if enough people complain then I'm fine with changing it.

**Comment by JensRantil** [comment]
Heh, second time you beat me to a comment! :-) I was just about to comment the same. A different approach would be to have a second `destination_status`.

Above said, I think the issue at hand is that `required_approvals` likely should be taken from the destination branch. Would you agree?

**Comment by notriddle** [comment]
> this means that any user could relax the security requirements by simply making a pull request

This means that a *rogue user with the r+ bit* could relax the security requirements by simply making a pull request. A rogue *user's* PR has no effect unless someone r+'es it. That's why the list of approved reviewers is being maintained in the web UI, rather than the bors.toml file; the contents of bors.toml are untrusted until a reviewer says they're trusted. And reviewers are totally trusted, in any case, since they can access the settings page in the dashboard.

The list of people who can r+ a pull request *doesn't have to be the same as the list of people who can make GitHub Reviews*. If you want somebody to be looking at the code without having permission to push it to prod, you can do that by making them GitHub repository collaborators without making them reviewers in bors.

**Comment by JensRantil** [comment]
Yep, sorry I was a bit vague. Our intention is to use bors-ng for an internal/private repository only, so the set of _users_ will always be equal to the set of _members_ in our case. My requirements are these:

 * All team members must have read access to a repository.
 * _Any_ team member must be able to be able to get changes in as long as a different team member approves the work.
 * Any team member must not be able to sidestep this process by disabling the four-eye rule. I love soft rules, but in this case we must have fixed controls in place. Either the rule must be disabled by an admin or, even better, the rule can be disabled as long as another team member approves it.

Do you think bors-ng would be somehow able to accomodate for these requirements? Maybe I'm missing someway of doing this with Github/bors-ng permissions.

**Comment by notriddle** [comment]
GitHub allows you to require a certain number of GH Reviews before it'll allow the pull request to merge. That setting still works when bors-ng is used, and it isn't subject to what's in bors.toml
