### ISSUE TITLE
Crash when `bors r+` a PR

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#398]
I'm getting the following every time I'm `bors r+`ing a specific PR:

```
{{:badmatch, {:error, :force_push}},
 [{BorsNG.GitHub, :synthesize_commit!, 2,
   [file: 'lib/github/github.ex', line: 88]},
  {BorsNG.Worker.Batcher, :start_waiting_merged_batch, 4,
   [file: 'lib/worker/batcher.ex', line: 295]},
  {BorsNG.Worker.Batcher, :start_waiting_batch, 1,
   [file: 'lib/worker/batcher.ex', line: 269]},
  {BorsNG.Worker.Batcher, :poll, 1,
   [file: 'lib/worker/batcher.ex', line: 200]},
  {BorsNG.Worker.Batcher, :handle_info, 2,
   [file: 'lib/worker/batcher.ex', line: 182]},
  {:gen_server, :try_dispatch, 4,
   [file: 'gen_server.erl', line: 601]},
  {:gen_server, :handle_msg, 5,
   [file: 'gen_server.erl', line: 667]},
  {:proc_lib, :init_p_do_apply, 3,
   [file: 'proc_lib.erl', line: 247]}]}
```

@Yopi If you have time, could you fill in some more details here? For example, what messages did we write to bors (`r+` etc.)? Also, did we open or close the PR? Any other theories what might have gone wrong?

**Comment by Yopi** [comment]
I believe I ran `bors r+`, which failed (because tests were failing). I then rebased and force pushed some things. After that `bors r+` has been breaking with this error. I have also tried opening up a new PR (closing the first one), cherry picking the commits into a third PR (closing the second PR). Same errors with both. We have also tried restarting bors-ng.

It sounds, from the error, like the problem was force pushing into a branch that bors had already ran on. But it feels like any of the things we tried after should have solved it.

**Comment by notriddle** [comment]
Do you have the staging branch set up as a protected branch?

**Comment by Yopi** [comment]
Yes the staging branch is set up as a protected branch.

**Comment by Yopi** [comment]
Removed the protected branch and it worked like a charm. You can close this issue @JensRantil!

**Comment by notriddle** [comment]
Yeah, it can't be a protected branch. Sorry.
