### ISSUE TITLE
Can't list repositories unless "Reviewer"

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#406]
The page `/repositories` doesn't list a repository unless the user is added as a reviewer for that repository. Since presenting the "Pull requests" and "History" doesn't really present any security issue, I propose that "Members" are allowed to access those tabs for a repository.

Why? Because "Pull requests" actually has a useful list of pull requests also for non-reviewers.

Also, the `/` page should likely also list the pull requests for repositories a user is a _member_ of.

What do you think of this proposal?

**Comment by notriddle** [comment]
Weird situation: if your bors instance is configured to disallow private repos (like [app.bors.tech] is) it will allow anyone to see the "Pull requests" tab. Try visiting https://app.bors.tech/repositories/4/. It doesn't work if the instance allows private repos, because #204 hasn't been fixed.

[app.bors.tech]: https://app.bors.tech/

As for the member things, you're right. It should probably show member repos in the dashboard and repository list, in addition to reviewer repos.

**Comment by JensRantil** [comment]
Ouch, I should have mentioned I'm running our own instance of bors-ng allowing private repositories and these are private repositories I'm talking about. 

Reading the description in #204 it doesn't really mention the private reposes should be viewable, though, so I'm not sure I should close this issue?
