### ISSUE TITLE
Rely on Github permissions figure out read permissions for a repository

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#409]
[Currently](407) making a user a "member" gives that user [limited](408) read-only access to the repository. Since Github actually comes with its own ACLs for Github reposes. Would it make sense to allow all users with read-access to a repo to also be able to see it in bors-ng (both dashboard and details as described in #408)?

**Comment by notriddle** [comment]
There are basically two ideas for how to do that:

* We can use GitHub's API to check whether the user can access the repo. That would actually be pretty bad, though, because it means hitting the API every time the user tries to open a page, which would double the page load time.

* We can try to sync down the ACL information. That's probably better, though a bit more complicated, and linked to #360.
