### ISSUE TITLE
Crash batch push 422

### ISSUE THREAD

**Issue by ForsakenHarmony** [bors-ng/bors-ng#561]
Could this happen because master is protected? 

```
{{:badmatch, {:error, :push, 422}},  [    {BorsNG.Worker.Batcher, :complete_batch, 3,     [file: 'lib/worker/batcher.ex', line: 386]},    {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,     [file: 'lib/worker/batcher.ex', line: 373]},    {BorsNG.Worker.Batcher, :handle_cast, 2,     [file: 'lib/worker/batcher.ex', line: 81]},    {:gen_server, :try_dispatch, 4,     [file: 'gen_server.erl', line: 637]},    {:gen_server, :handle_msg, 6,     [file: 'gen_server.erl', line: 711]},    {:proc_lib, :init_p_do_apply, 3,     [file: 'proc_lib.erl', line: 249]}  ]}
```

**Comment by zegl** [comment]
This also seems to happen if is an open negative review ("request changes") open on the PR. 

It would be nice if bors was more helpful in this situation, and posted a message as a PR comment, instead of crashing. Users that doesn't have bors reviewer access doesn't have access to look at the crash logs either, which makes this error frustrating for the user.

**Comment by ForsakenHarmony** [comment]
Well I figured out it happens when reviews are required and you try to merge with bors before approving

**Comment by umamaistempo** [comment]
I'll be taking a look on this issue. Hopefully I'll be shipping a fix on friday or monday (tomorrow is a holiday here)

**Comment by umamaistempo** [comment]
This kind of problem should not occur anymore. In case anything similar or derived from this error occurs, feel free to create a new issue and tag me

**Comment by umamaistempo** [comment]
@notriddle please close this

**Comment by notriddle** [comment]
Sure, okay.

If anyone else runs into it, @ me so I can reopen.
