### ISSUE TITLE
Using GH internal references instead of staging/trying

### ISSUE THREAD

**Issue by nox** [bors-ng/bors-ng#577]
Instead of creating and maintaining staging/trying branches, would there be any way to use the Travis API to trigger builds of `pull/123/merge`? This way there would be no difference between what Travis does on its on with pull request builds and what Bors wants to do.

**Comment by notriddle** [comment]
That means bors can't control what the commit message is, can't do batching, and that it has to be tied specifically to Travis CI's API.

Especially considering that last point, is there any reason you couldn't implement what you want in a very simple GitHub Action? Since it wouldn't support more than one CI provider and wouldn't do any batching, it could probably be completely stateless. https://mgattozzi.com/github-actions-an-introductory-look-and-first-impressions/
