### ISSUE TITLE
Infer the use of Azure Pipelines based on its config file

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#592]
Bors-NG has an (at present undocumented) ability to infer what CI system you're using without a `bors.toml` file. It doesn't support Azure DevOps Pipelines at present.

According to [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=azure-devops&viewFallbackFrom=vsts), the config file is in `azure-pipelines.yml`. To add a new bors.toml inference rule, [put it in the `GetBorsToml` module](https://github.com/bors-ng/bors-ng/blob/239932148799c77313d092433ef7ff1c01bc82f0/lib/worker/batcher/get_bors_toml.ex#L25-L33).

See also:

* https://github.com/bors-ng/bors-ng/issues/104
* https://github.com/bors-ng/bors-ng/issues/103

**Comment by ericsolomon** [comment]
I'll take this issue. I'll submit a PR later tonight. Still working through the repo.

**Comment by TheoLeanse** [comment]
@ericsolomon are you still working on this? Happy to take it on if not :)

**Comment by ericsolomon** [comment]
@TheoLeanse go for it. Work caught up with me so I haven't had a chance to look into what the status identifier for azure is.

**Comment by TheoLeanse** [comment]
Okie Dokie - the issue here is that the GitHub Status for an Azure Pipelines build appears to be the name of the individual Azure Pipeline itself, rather than something nice and generic like `ci/circleci`. 

In this case I'm not sure if Azure Pipelines can be used without a `bors.toml` to explictly include the Pipeline name - I wondered if the Pipeline name could be derived from the project's `azure-pipelines.yml` but this does not seem to be possible.

**Comment by notriddle** [comment]
Then I guess we can close the issue then?

Sorry about that.
