### ISSUE TITLE
COMMAND_TRIGGER seems to not be respected

### ISSUE THREAD

**Issue by johnae** [bors-ng/bors-ng#673]
Trying the latest docker image over at docker hub in kubernetes and setting COMMAND_TRIGGER to something other than bors doesn't actually do anything. Perhaps it did at one time since the README suggests that but it still seems to listen only to `bors`. Eg. if I set the COMMAND_TRIGGER to say `bleh` it won't listen to that if I do `bleh ping` - still just listens to `bors` (and `bros` for some things).

**Comment by umamaistempo** [comment]
The `bros` command is an easter egg :joy:

```elixir
def run(c, :bros) do
    c.project.repo_xref
    |> Project.installation_connection(Repo)
    |> GitHub.post_comment!(
      c.pr_xref, ~s/👊/)
  end
```

Also, the COMMAND_TRIGGER is identified at compile-time, so, you have to ensure that elixir recompiled after you configured it.

TBH I'm not sure how it works out on Heroku as I've never used it, but if you can't find it (how to recompile) or recompiling doesn't solve it, respond to this issue again and I'll take a look :)

**Comment by johnae** [comment]
@umamaistempo Hmm ok. Compile time? It doesn't say anything about that in the README but rather mentions that the environment variable `COMMAND_TRIGGER` would determine this...

**Comment by johnae** [comment]
This is the pull request that enabled this I believe: https://github.com/bors-ng/bors-ng/pull/461

**Comment by umamaistempo** [comment]
Sorry, this is an implementation detail and those configs (pool size, public host, command trigger, secret key etc) are not changed frequently, so the code was built considering that once set they would always be the same.

To change this, it would require a minor refactor on the command part of the code, which is not a big deal but I am unsure whether this case is common and if we have to treat it...

**Comment by johnae** [comment]
Are you saying the README is misleading regarding running this in docker then? Because the other environment variables seemed to work just fine...

**Comment by umamaistempo** [comment]
Hello @johnae . The README is not missleading, it just does not mention that this in particular was something defined on compilation and since something like this has never happened, it never changed to be dynamically set (no one even noticed it probably) as originally the value would always be set as Bors.

**Comment by johnae** [comment]
But isn't it misleading to talk about starting a container with an env var that supposedly sets the trigger when that can never work (even though in the specific case it is being set to `bors` which wouldn't really change anything). That env var can't really be useful for anything in that context right? Until that pull request gets merged at least. Thanks for looking into this anyway!

**Comment by umamaistempo** [comment]
This is more of an overlook IMO. This config was changed to receive a value from the ENV; before it would have to be changed from the config file and whenever a config file is changed the code is recompiled because of this.
So looking this way, I think that I understand better what you saying and yes, this is a bug because it can't react to env changes but who envisioned the deploy might have envisioned with it always recompiling before starting (as compilation in elixir/erlang is very cheap)

**Comment by notriddle** [comment]
Yes, it's misleading. And it definitely should be fixed (just r+-ed a PR that'll fix it, so just update).
