### ISSUE TITLE
Why does bors close PRs instead of merging them?

### ISSUE THREAD

**Issue by roni-frantchi** [bors-ng/bors-ng#899]
I used to use this one a few years back when it just started.  
I had the recollection that back then, `bors-ng` actually used to merge PRs after a successful build on `staging`, not close them and then merge from `staging`.  

Was wondering what's the idea behind that change of behavior @notriddle ?
And is there a way to make bors actually merge PRs instead of closing them

**Comment by DilumAluthge** [comment]
Are you using the squash-merge feature of Bors?

**Comment by roni-frantchi** [comment]
Yes I am. Is that what's causing it @DilumAluthge ?  
Cause I actually would like to squash-merge. Why is it that it happens when using squash?

**Comment by DilumAluthge** [comment]
Because of a current limitation in how GitHub works, if Bors squash-merges a PR, GitHub will not automatically recognize that the PR was merged. Therefore GitHub will not mark the PR as merged, and instead will leave the PR open. So Bors has to manually close the PR.

The GitHub API does not allow anyone to mark a PR as merged. Our only options are to mark the PR as open or mark it as closed.

If you do not use squash-merge, then when Bors regular-merges the PR, GitHub's system magically automatically detects that the PR was merged, and therefore GitHub marks the PR as merged.

**Comment by DilumAluthge** [comment]
The options are:
1. Use the regular-merge option in Bors. Then PRs will be marked as merged (purple).
2. Use the squash-merge option in Bors. Then PRs will be marked as closed (red).

Unfortunately there is no way to fix this on the Bors end. It needs new functionality implemented on GitHub's end.

**Comment by roni-frantchi** [comment]
Thanks for explaining @DilumAluthge .  
Does that mean that if I were to turn off squash-merge on bors, it will fail to merge unless I change the following setting on GH?  
![image](https://user-images.githubusercontent.com/3658029/76007055-1edde800-5f16-11ea-9a0a-03302e2fdcbe.png)

**Comment by roni-frantchi** [comment]
I guess there's public API that will allow the same interaction as clicking that Merge button?. basically asking GH to Squash merge a PR?..

**Comment by roni-frantchi** [comment]
Is [this API](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button) the one that's being used @DilumAluthge ?..

**Comment by DilumAluthge** [comment]
We do not use that API.

The benefits of Bors is that the code on staging is exactly what master is fast-forwarded to.

If we used that API, we would lose that guarantee.

**Comment by roni-frantchi** [comment]
@DilumAluthge 
What would happen if bors would fast forward and merge exactly as you're doing right now when squash-merge is set, and only then you'd call that API?  
Would it make GH mark it as merged without actually creating the commit? Create an empty commit?..  
Or fail?..

**Comment by DilumAluthge** [comment]
> @DilumAluthge
> What would happen if bors would fast forward and merge exactly as you're doing right now when squash-merge is set, and only then you'd call that API?
> Would it make GH mark it as merged without actually creating the commit? Create an empty commit?..
> Or fail?..

You'd end up creating duplicate commits. You'd have the commit Bors made, and then the commit from GitHub's "big green button" API.

**Comment by DilumAluthge** [comment]
Or it would fail.

**Comment by roni-frantchi** [comment]
> You'd end up creating duplicate commits

If they're empty, maybe that's a fair alternative?. Obviously far from ideal, but possibly better than breaking all sorts of down stream events and automation due to PRs not being properly merged?..

I wonder if there isn't a way to guarantee no code changes slipped in if we were to use the merge button API...

**Comment by DilumAluthge** [comment]
If there are duplicate commits, I don't think they would be empty.

In general, I don't think GitHub makes any guarantees about what happens if you try to click the big green button after you have manually squash-merged yourself.

**Comment by roni-frantchi** [comment]
@DilumAluthge I ran the exercise of reopening the PR closed by bors and hitting the Squash and Merge button.  
The end result was a duplicate, empty commit:

<img width="1007" alt="Screen Shot 2020-03-07 at 12 53 12" src="https://user-images.githubusercontent.com/3658029/76142069-cd973b00-6072-11ea-8510-7509153cbb1f.png">

<img width="961" alt="Screen Shot 2020-03-07 at 12 52 45" src="https://user-images.githubusercontent.com/3658029/76142067-cb34e100-6072-11ea-8c09-74719b35ed4d.png">

Would it be acceptable to expose a configuration to allow make bors behave this way?

**Comment by DilumAluthge** [comment]
That would be a question for @notriddle.

Personally I don't want my git history full of duplicate commits even if they are empty.

**Comment by roni-frantchi** [comment]
Yeah, me neither @DilumAluthge .  
But if I do have to pick my poison between:
1. Giving up squash merge and having `master` littered with merged commits
2. Having my PR history all showing as closed, and not triggering any downstream PR-merged hooks
3. Having a duplicate empty squash commit  

I may consider choosing the latter

**Comment by notriddle** [comment]
No, I don't think I'd approve an RFC for the third option. The empty squash commits don't seem any better than the merge commits.

**Comment by carlos-granados** [comment]
Since, in order to fix this, Github would need to implement something on their side (I guess that the option to set a PR as merged through the API), has this been requested by opening a ticket with Github?

**Comment by Gabriella439** [comment]
We managed to fix this in our fork of `bors-ng` here:

https://github.com/MercuryTechnologies/bors-ng/commit/d57528b5ed6701cf0b12b253d348d2d4dc1798f9

Basically the approach that change takes is that once the PR is accepted you throw away the staging branch and use GitHub's API to squash merge the original PRs onto the base branch in the same order that they were tested.  This correctly marks them merged instead of closed.

This approach doesn't break if the authors push new changes to the PRs after they are queued and before they are merged because `bors-ng` already cancels the batch when this happens.

I can open a PR for this if the maintainers are willing to accept it.

**Comment by Gabriella439** [comment]
So there is an alternative way to do this that avoids the TOCTOU issue but it requires clobbering the PR commit history

What you can do is that after the staging branch is validated, then:

- for each new squashed commit in the staging branch
  - force push the parent of the squashed commit to the trunk branch
  - force push the squashed commit to the original PR
- finally, force push the last squashed commit to the trunk branch

If you do that then GitHub will mark every PR as merged because the PR's commit matches what was pushed to the trunk branch.

The downside is that this deletes the PR commit history and you can't fix the PR history with another force push once it's marked merged.  I didn't go that route, though, because most users want to preserve the original commit history on their commits, so I figured the approach that I ultimately implemented was the lesser of two evils.
